### ISSUE TITLE
Assertion failed: window != NULL

### ISSUE THREAD

**Issue by User7142** [siddharthroy12/kosmos#1]
Hi, wenn I try to start the game (kosmos.exe) I get only this error:

`Assertion failed: window != NULL, file /home/siddharth/Projects/kosmos/libs/raylib/src/external/glfw/src/window.c, line 875`

I'm on Windows 10 Pro - Build: 20H2 and got the Windows-Version 1.0 from https://github.com/siddharthroy12/kosmos/releases/tag/v1.0

Anything I can do against this error? Thanks.

**Comment by siddharthroy12** [comment]
Can you tell me what version of OpenGL does your machine support and is your machine 64bit?

**Comment by User7142** [comment]
Sure: It is a Intel HD 2000, which supports OpenGL 3.1.  And yes it is the 64 bit Version of Windows 10.

**Comment by siddharthroy12** [comment]
Oh, That's why I've compiled it for OpenGL 3.3, I'll downgrade to 3.1 soon.

**Comment by User7142** [comment]
For me, you don't need to make the effort. I'll be changing computers in the next few days and will then have an Nvidia GTX 680 with OpenGL 4.6 at my service. I hope that it will run then. But thanks for the info.

**Comment by siddharthroy12** [comment]
I did it anyway because I want to support as many machines as possible. Check the v1.01 release

**Comment by User7142** [comment]
Thanks, sadly I got still the same error, but I just switched to the GTX 680 and it is working without problems here. 

Btw.: You shouldn't be able to shoot from outside the blue circle otherwise this game is too easy.

**Comment by siddharthroy12** [comment]
Yeah I'm still working on improving the game
